# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75555b6e8c48712911aac95230003e06b972575d24990a5c7e6bb2c528e5186ea1803ac5dd684f7b60dc5da531ee53b6bd4492ff7e1c681e2858c0bb591d7918

test:
  secret_key_base: 016de4e9541f49411b5cebcc2b7fb3229710cb4cc261f4c3a423e5c6bed5e27feb34927bace8f64f26aebc33c2b0b6becbb4dff5495570a1609d7490e4b49308

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
